package com.mycompany.a1;


import java.io.IOException;

import javax.swing.JFrame;

/**
 * This file was generated by <a href="https://www.codenameone.com/">Codename One</a> for the purpose 
 * of building native mobile applications using Java.
 */
public class Starter {

    private JFrame current;
  

    public void init(Object context) {
        // use two network threads instead of one
        
    }
    
    public void start() {
        if(current != null){
            current.show();
            return;
        }
        new Game();
    }

    public void stop() {
      
    }
    
    public void destroy() {
    }

    public static void main(String[] args) {
		Ant a = new Ant(0, 0, 1, 1);
		System.out.println(a.toString());
		a.move(1, 10);
		System.out.println(a.toString());
		a.move(1, 10);
		System.out.println(a.toString());
		a.move(1, 10);
		System.out.println(a.toString());
		Flag f1 = new Flag(1, 1, 1);
		System.out.println(f1.toString());
		Flag f2= new Flag(1, 3, 2);
		System.out.println(f2.toString());
	}
}
